# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_auto_20160328_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='student_id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
