# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_auto_20160328_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='schedulemodel',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
        migrations.DeleteModel(
            name='ScheduleModel',
        ),
    ]
