# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0010_auto_20160328_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
