# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0011_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
