# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0014_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_title', models.CharField(max_length=120)),
                ('e_desc', models.TextField()),
                ('e_date', models.DateField()),
                ('e_time', models.TimeField()),
                ('e_end_date', models.DateField()),
                ('e_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('sch_date', models.DateField()),
                ('sch_time', models.TimeField()),
                ('reminder_time', models.TimeField()),
                ('reminder_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.UserModel')),
            ],
        ),
    ]
